import ActionLocationType from '#server/models/actionModel/fetch/ActionLocationType.d';

export type ActionInput = {
    name: string,
    started_at: Date,
    ended_at: Date | null,
    goals: string | null,
    topics: string[],
    location_departement: string,
    location_type: ActionLocationType,
    managers: number[],
    operators: number[],
    location_eti: string | null,
    latitude: number | null,
    longitude: number | null,
    location_shantytowns: number[] | null,
    location_other: string | null,
    nombre_personnes: number,
    nombre_menages: number | null,
    nombre_femmes: number | null,
    nombre_mineurs: number | null,
    sante_nombre_personnes: number | null,
    travail_nombre_personnes: number | null,
    travail_nombre_femmes: number | null,
    hebergement_nombre_personnes: number | null,
    hebergement_nombre_menages: number | null,
    logement_nombre_personnes: number | null,
    logement_nombre_menages: number | null,
    scolaire_mineurs_scolarisables: number | null,
    scolaire_mineurs_en_mediation: number | null,
    scolaire_nombre_maternelle: number | null,
    scolaire_nombre_elementaire: number | null,
    scolaire_nombre_college: number | null,
    scolaire_nombre_lycee: number | null,
    scolaire_nombre_autre: number | null,
};
