export type DepartementObject = {
    departement: string,
    data: []
};

export type ActionItem = {
    departement_name: string,
    region_code: string,
    region_name: string,
    action_id: number,
    action_name: string,
    started_at: string,
    ended_at: string | null,
    location_type: string,
    topics: string[],
    goals: string,
    nombre_personnes: number | null,
    nombre_menages: number | null,
    nombre_femmes: number | null,
    nombre_mineurs: number | null,
    sante_nombre_personnes: number | null,
    travail_nombre_personnes: number | null,
    travail_nombre_femmes: number | null,
    hebergement_nombre_personnes: number | null,
    hebergement_nombre_menages: number | null,
    logement_nombre_personnes: number | null,
    logement_nombre_menages: number | null,
    scolaire_mineurs_scolarisables: number | null,
    scolaire_mineurs_en_mediation: number | null,
    scolaire_nombre_maternelle: number | null,
    scolaire_nombre_elementaire: number | null,
    scolaire_nombre_college: number | null,
    scolaire_nombre_lycee: number | null,
    scolaire_nombre_autre: number | null,
    finance_etatique: number | null,
    finance_dedie: number | null,
    finance_collectivite: number | null,
    finance_europeen: number | null,
    finance_prive: number | null,
    finance_autre: number | null,
    depense_finance_etatique: number | null,
    depense_finance_dedie: number | null,
    depense_finance_collectivite: number | null,
    depense_finance_europeen: number | null,
    depense_finance_prive: number | null,
    depense_finance_autre: number | null,
    comments: string | null,
    last_comment: string | null,
    last_comment_date: string | null,
    last_update: string | null,
};
