export type ShantytownRow = {
    id: number,
    name: string | null,
    status: 'open' | 'unknown' | 'closed_by_justice' | 'resorbed' | 'other',
    closingContext: string | null
    declaredAt: Date,
    builtAt: Date,
    closedAt: Date,
    latitude: number,
    longitude: number,
    address: string,
    isReinstallation: boolean | null,
    reinstallationComments: string | null,
    addressDetails: string | null,
    populationTotal: number | null,
    populationCouples: number | null,
    populationMinors: number | null,
    populationMinors0To3: number | null,
    populationMinors3To6: number | null,
    populationMinors6To12: number | null,
    populationMinors12To16: number | null,
    populationMinors16To18: number | null,
    minorsInSchool: number | null,
    caravans: number | null,
    huts: number | null,
    tents: number | null,
    cars: number | null,
    mattresses: number | null,
    livingConditionsVersion: 1 | 2,
    accessToSanitary: boolean | null,
    sanitaryComments: string | null,
    accessToWater: boolean | null,
    waterComments: string | null,
    trashEvacuation: boolean | null,
    owner: string | null,
    censusStatus: 'done' | 'scheduled' | null,
    censusConductedBy: string | null,
    censusConductedAt: Date | null,
    ownerComplaint: boolean | null,
    justiceProcedure: boolean | null,
    justiceRendered: boolean | null,
    justiceRenderedAt: Date | null,
    justiceRenderedBy: string | null,
    justiceChallenged: boolean | null,
    policeStatus: 'requested' | 'granted' | 'none' | null,
    policeRequestedAt: Date | null,
    policeGrantedAt: Date | null,
    bailiff: string | null,
    // procédures administratives
    existingLitigation: boolean | null,
    evacuationUnderTimeLimit: boolean | null,
    administrativeOrderDecisionAt: Date | null,
    administrativeOrderDecisionRenderedBy: string | null,
    administrativeOrderEvacuationAt: Date | null,
    insalubrityOrder: boolean | null,
    insalubrityOrderDisplayed: boolean | null,
    insalubrityOrderType: string | null,
    insalubrityOrderBy: string | null,
    insalubrityOrderAt: Date | null,
    insalubrityParcels: string | null,
    // fin procédures administratives
    closedWithSolutions: 'yes' | 'no' | 'unknown' | null,
    createdAt: Date,
    updatedAt: Date,
    heatwaveStatus: boolean,
    waterPotable: boolean | null,
    waterContinuousAccess: boolean | null,
    waterPublicPoint: boolean | null,
    waterDistance: string | null,
    waterRoadsToCross: boolean | null,
    waterEveryoneHasAccess: boolean | null,
    waterStagnantWater: boolean | null,
    waterHandWashAccess: boolean | null,
    waterHandWashAccessNumber: number | null,
    sanitaryNumber: number | null,
    sanitaryInsalubrious: boolean | null,
    sanitaryOnSite: boolean | null,
    trashCansOnSite: number | null,
    trashAccumulation: boolean | null,
    trashEvacuationRegular: boolean | null,
    vermin: boolean | null,
    verminComments: string | null,
    firePreventionMeasures: boolean | null,
    firePreventionDiagnostic: boolean | null,
    firePreventionSiteAccessible: boolean | null,
    firePreventionDevices: boolean | null,
    firePreventionComments: string | null,
    resorptionTarget: number | null,
    createdById: number,
    createdByFirstName: string,
    createdByLastName: string,
    createdByPosition: string,
    createdByOrganization: number,
    createdByOrganizationName: string,
    createdByOrganizationAbbreviation: string | null,
    updatedById: number,
    updatedByFirstName: string,
    updatedByLastName: string,
    updatedByPosition: string,
    updatedByOrganization: number,
    updatedByOrganizationName: string,
    updatedByOrganizationAbbreviation: string | null,
    cityCode: string,
    cityName: string,
    cityMain: string | null,
    cityLatitude: number,
    cityLongitude: number,
    epciCode: string | null,
    epciName: string | null,
    departementCode: string,
    departementName: string,
    departementLatitude: number,
    departementLongitude: number,
    departementChiefTownCode: string,
    departementChiefTownName: string,
    departementChiefTownLatitude: number
    departementChiefTownLongitude: number,
    regionCode: string,
    regionName: string,
    regionLatitude: number,
    regionLongitude: number,
    regionChiefTownCode: string,
    regionChiefTownName: string,
    regionChiefTownLatitude: number,
    regionChiefTownLongitude: number,
    electricityTypeId: number | null,
    electricityTypeUid: string | null,
    electricityTypeLabel: string | null,
    electricityComments: string | null,
    fieldTypeId: number,
    fieldTypeLabel: string,
    ownerTypeId: number,
    ownerTypeLabel: string,
    waterAccessType: string | null,
    waterAccessTypeDetails: string | null,
    waterAccessIsPublic: boolean | null,
    waterAccessIsContinuous: boolean | null,
    waterAccessIsContinuousDetails: string | null,
    waterAccessIsLocal: boolean | null,
    waterAccessIsClose: boolean | null,
    waterAccessIsUnequal: boolean | null,
    waterAccessIsUnequalDetails: boolean | null,
    waterAccessHasStagnantWater: boolean | null,
    waterAccessComments: string | null,
    sanitaryAccessOpenAirDefecation: boolean | null,
    sanitaryAccessWorkingToilets: boolean | null,
    sanitaryAccessToiletsAreInside: boolean | null,
    sanitaryAccessToiletsAreLighted: boolean | null,
    sanitaryAccessHandWashing: boolean | null,
    electricityAccess: boolean | null,
    electricityAccessIsUnequal: boolean | null,
    trashIsPiling: boolean | null,
    trashEvacuationIsClose: boolean | null,
    trashEvacuationIsSafe: boolean | null,
    trashEvacuationIsRegular: boolean | null,
    trashBulkyIsPiling: boolean | null,
    pestAnimals: boolean | null,
    pestAnimalsDetails: string | null,
    firePrevention: boolean | null,
    socialOrigins: string[],
    electricityAccessTypes: string[],
    toiletTypes: string[],
    distance?: number | null

};

export default {
    selection: {
        'shantytowns.shantytown_id': 'id',
        'shantytowns.name': 'name',
        'shantytowns.status': 'status',
        'shantytowns.closing_context': 'closingContext',
        'shantytowns.declared_at': 'declaredAt',
        'shantytowns.built_at': 'builtAt',
        'shantytowns.closed_at': 'closedAt',
        'shantytowns.latitude': 'latitude',
        'shantytowns.longitude': 'longitude',
        'shantytowns.address': 'address',
        'shantytowns.is_reinstallation': 'isReinstallation',
        'shantytowns.reinstallation_comments': 'reinstallationComments',
        'shantytowns.address_details': 'addressDetails',
        'shantytowns.population_total': 'populationTotal',
        'shantytowns.population_couples': 'populationCouples',
        'shantytowns.population_minors': 'populationMinors',
        'shantytowns.population_minors_0_3': 'populationMinors0To3',
        'shantytowns.population_minors_3_6': 'populationMinors3To6',
        'shantytowns.population_minors_6_12': 'populationMinors6To12',
        'shantytowns.population_minors_12_16': 'populationMinors12To16',
        'shantytowns.population_minors_16_18': 'populationMinors16To18',
        'shantytowns.minors_in_school': 'minorsInSchool',
        'shantytowns.caravans': 'caravans',
        'shantytowns.huts': 'huts',
        'shantytowns.tents': 'tents',
        'shantytowns.cars': 'cars',
        'shantytowns.mattresses': 'mattresses',
        'shantytowns.living_conditions_version': 'livingConditionsVersion',
        'shantytowns.access_to_sanitary': 'accessToSanitary',
        'shantytowns.sanitary_comments': 'sanitaryComments',
        'shantytowns.access_to_water': 'accessToWater',
        'shantytowns.water_comments': 'waterComments',
        'shantytowns.trash_evacuation': 'trashEvacuation',
        'shantytowns.owner': 'owner',
        'shantytowns.census_status::text': 'censusStatus',
        'shantytowns.census_conducted_by': 'censusConductedBy',
        'shantytowns.census_conducted_at': 'censusConductedAt',
        'shantytowns.owner_complaint': 'ownerComplaint',
        'shantytowns.justice_procedure': 'justiceProcedure',
        'shantytowns.justice_rendered': 'justiceRendered',
        'shantytowns.justice_rendered_at': 'justiceRenderedAt',
        'shantytowns.justice_rendered_by': 'justiceRenderedBy',
        'shantytowns.justice_challenged': 'justiceChallenged',
        'shantytowns.police_status::text': 'policeStatus',
        'shantytowns.police_requested_at': 'policeRequestedAt',
        'shantytowns.police_granted_at': 'policeGrantedAt',
        'shantytowns.bailiff': 'bailiff',
        // procédures administratives
        'shantytowns.existing_litigation': 'existingLitigation',
        'shantytowns.evacuation_under_time_limit': 'evacuationUnderTimeLimit',
        'shantytowns.administrative_order_decision_at': 'administrativeOrderDecisionAt',
        'shantytowns.administrative_order_decision_rendered_by': 'administrativeOrderDecisionRenderedBy',
        'shantytowns.administrative_order_evacuation_at': 'administrativeOrderEvacuationAt',
        'shantytowns.insalubrity_order': 'insalubrityOrder',
        'shantytowns.insalubrity_order_displayed': 'insalubrityOrderDisplayed',
        'shantytowns.insalubrity_order_type': 'insalubrityOrderType',
        'shantytowns.insalubrity_order_by': 'insalubrityOrderBy',
        'shantytowns.insalubrity_order_at': 'insalubrityOrderAt',
        'shantytowns.insalubrity_parcels': 'insalubrityParcels',
        // fin procédures administratives
        'shantytowns.closed_with_solutions::text': 'closedWithSolutions',
        'shantytowns.created_at': 'createdAt',
        'shantytowns.updated_at': 'updatedAt',
        // new fields
        'shantytowns.heatwave_status': 'heatwaveStatus',
        'shantytowns.water_potable': 'waterPotable',
        'shantytowns.water_continuous_access': 'waterContinuousAccess',
        'shantytowns.water_public_point': 'waterPublicPoint',
        'shantytowns.water_distance::text': 'waterDistance',
        'shantytowns.water_roads_to_cross': 'waterRoadsToCross',
        'shantytowns.water_everyone_has_access': 'waterEveryoneHasAccess',
        'shantytowns.water_stagnant_water': 'waterStagnantWater',
        'shantytowns.water_hand_wash_access': 'waterHandWashAccess',
        'shantytowns.water_hand_wash_access_number': 'waterHandWashAccessNumber',
        'shantytowns.sanitary_number': 'sanitaryNumber',
        'shantytowns.sanitary_insalubrious': 'sanitaryInsalubrious',
        'shantytowns.sanitary_on_site': 'sanitaryOnSite',
        'shantytowns.trash_cans_on_site': 'trashCansOnSite',
        'shantytowns.trash_accumulation': 'trashAccumulation',
        'shantytowns.trash_evacuation_regular': 'trashEvacuationRegular',
        'shantytowns.vermin': 'vermin',
        'shantytowns.vermin_comments': 'verminComments',
        'shantytowns.fire_prevention_measures': 'firePreventionMeasures',
        'shantytowns.fire_prevention_diagnostic': 'firePreventionDiagnostic',
        'shantytowns.fire_prevention_site_accessible': 'firePreventionSiteAccessible',
        'shantytowns.fire_prevention_devices': 'firePreventionDevices',
        'shantytowns.fire_prevention_comments': 'firePreventionComments',
        'shantytowns.resorption_target': 'resorptionTarget',
        'creators.user_id': 'createdById',
        'creators.first_name': 'createdByFirstName',
        'creators.last_name': 'createdByLastName',
        'creators.position': 'createdByPosition',
        'creators_organizations.organization_id': 'createdByOrganization',
        'creators_organizations.name': 'createdByOrganizationName',
        'creators_organizations.abbreviation': 'createdByOrganizationAbbreviation',
        'updators.user_id': 'updatedById',
        'updators.first_name': 'updatedByFirstName',
        'updators.last_name': 'updatedByLastName',
        'updators.position': 'updatedByPosition',
        'updators_organizations.organization_id': 'updatedByOrganization',
        'updators_organizations.name': 'updatedByOrganizationName',
        'updators_organizations.abbreviation': 'updatedByOrganizationAbbreviation',
        'cities.code': 'cityCode',
        'cities.name': 'cityName',
        'cities.fk_main': 'cityMain',
        'cities.latitude': 'cityLatitude',
        'cities.longitude': 'cityLongitude',
        'epci.code': 'epciCode',
        'epci.name': 'epciName',
        'departements.code': 'departementCode',
        'departements.name': 'departementName',
        'departements.latitude': 'departementLatitude',
        'departements.longitude': 'departementLongitude',
        // Departement chieftown
        'departementChiefTown.code': 'departementChiefTownCode',
        'departementChiefTown.name': 'departementChiefTownName',
        'departementChiefTown.latitude': 'departementChiefTownLatitude',
        'departementChiefTown.longitude': 'departementChiefTownLongitude',
        'regions.code': 'regionCode',
        'regions.name': 'regionName',
        'regions.latitude': 'regionLatitude',
        'regions.longitude': 'regionLongitude',
        'regionChiefTown.code': 'regionChiefTownCode',
        'regionChiefTown.name': 'regionChiefTownName',
        'regionChiefTown.latitude': 'regionChiefTownLatitude',
        'regionChiefTown.longitude': 'regionChiefTownLongitude',
        'electricity_types.electricity_type_id': 'electricityTypeId',
        'electricity_types.uid': 'electricityTypeUid',
        'electricity_types.label': 'electricityTypeLabel',
        'shantytowns.electricity_comments': 'electricityComments',
        'field_types.field_type_id': 'fieldTypeId',
        'field_types.label': 'fieldTypeLabel',
        'owner_types.owner_type_id': 'ownerTypeId',
        'owner_types.label': 'ownerTypeLabel',
        'shantytowns.water_access_type::text': 'waterAccessType',
        'shantytowns.water_access_type_details': 'waterAccessTypeDetails',
        'shantytowns.water_access_is_public': 'waterAccessIsPublic',
        'shantytowns.water_access_is_continuous': 'waterAccessIsContinuous',
        'shantytowns.water_access_is_continuous_details': 'waterAccessIsContinuousDetails',
        'shantytowns.water_access_is_local': 'waterAccessIsLocal',
        'shantytowns.water_access_is_close': 'waterAccessIsClose',
        'shantytowns.water_access_is_unequal': 'waterAccessIsUnequal',
        'shantytowns.water_access_is_unequal_details': 'waterAccessIsUnequalDetails',
        'shantytowns.water_access_has_stagnant_water': 'waterAccessHasStagnantWater',
        'shantytowns.water_access_comments': 'waterAccessComments',
        'shantytowns.sanitary_access_open_air_defecation': 'sanitaryAccessOpenAirDefecation',
        'shantytowns.sanitary_access_working_toilets': 'sanitaryAccessWorkingToilets',
        'shantytowns.sanitary_access_toilets_are_inside': 'sanitaryAccessToiletsAreInside',
        'shantytowns.sanitary_access_toilets_are_lighted': 'sanitaryAccessToiletsAreLighted',
        'shantytowns.sanitary_access_hand_washing': 'sanitaryAccessHandWashing',
        'shantytowns.electricity_access': 'electricityAccess',
        'shantytowns.electricity_access_is_unequal': 'electricityAccessIsUnequal',
        'shantytowns.trash_is_piling': 'trashIsPiling',
        'shantytowns.trash_evacuation_is_close': 'trashEvacuationIsClose',
        'shantytowns.trash_evacuation_is_safe': 'trashEvacuationIsSafe',
        'shantytowns.trash_evacuation_is_regular': 'trashEvacuationIsRegular',
        'shantytowns.trash_bulky_is_piling': 'trashBulkyIsPiling',
        'shantytowns.pest_animals': 'pestAnimals',
        'shantytowns.pest_animals_details': 'pestAnimalsDetails',
        'shantytowns.fire_prevention': 'firePrevention',
    },
    joins: [
        { table: 'owner_types', on: 'shantytowns.fk_owner_type = owner_types.owner_type_id' },
        { table: 'field_types', on: 'shantytowns.fk_field_type = field_types.field_type_id' },
        { table: 'electricity_types', on: 'shantytowns.fk_electricity_type = electricity_types.electricity_type_id' },
        { table: 'cities', on: 'shantytowns.fk_city = cities.code' },
        { table: 'epci', on: 'cities.fk_epci = epci.code' },
        { table: 'departements', on: 'cities.fk_departement = departements.code' },
        { table: 'cities AS departementChiefTown', on: 'departementChiefTown.code = departements.fk_city' },
        { table: 'regions', on: 'departements.fk_region = regions.code' },
        { table: 'cities AS regionChiefTown', on: 'regionChiefTown.code = regions.fk_city' },
        { table: 'users AS creators', on: 'shantytowns.created_by = creators.user_id' },
        { table: 'organizations AS creators_organizations', on: 'creators.fk_organization = creators_organizations.organization_id' },
        { table: 'users AS updators', on: 'shantytowns.updated_by = updators.user_id' },
        { table: 'organizations AS updators_organizations ', on: 'updators.fk_organization = updators_organizations.organization_id' },
        { table: 'shantytown_actors ', on: 'shantytown_actors.fk_shantytown = shantytowns.shantytown_id AND shantytown_actors.fk_user = :userId' },
    ],
};
