import { City } from '#server/models/geoModel/Location.d';
import { Shantytown } from '#root/types/resources/Shantytown.d';
import locations from './location';
import fakeUser from './user';

const defaultLocation = locations.paris.city();

export function creationInput() {
    return {
        name: global.generate('string'),
        latitude: global.generate('string'),
        longitude: global.generate('string'),
        address: global.generate('string'),
        detailed_address: global.generate('string'),
        built_at: global.generate('string'),
        population_total: global.generate('string'),
        population_total_females: global.generate('string'),
        population_couples: global.generate('string'),
        population_minors: global.generate('string'),
        population_minors_girls: global.generate('string'),
        population_minors_0_3: global.generate('string'),
        population_minors_3_6: global.generate('string'),
        population_minors_6_12: global.generate('string'),
        population_minors_12_16: global.generate('string'),
        population_minors_16_18: global.generate('string'),
        minors_in_school: global.generate('string'),
        caravans: global.generate('string'),
        huts: global.generate('string'),
        tents: global.generate('string'),
        cars: global.generate('string'),
        mattresses: global.generate('string'),
        field_type: global.generate('string'),
        owner_type: global.generate('string'),
        is_reinstallation: global.generate('string'),
        reinstallation_comments: global.generate('string'),
        reinstallation_incoming_towns_full: [{ id: 1 }, { id: 2 }, { id: 3 }],
        citycode: global.generate('string'),
        declared_at: global.generate('string'),
        census_status: global.generate('string'),
        census_conducted_at: global.generate('string'),
        census_conducted_by: global.generate('string'),
        social_origins: global.generate('string'),

        owner_complaint: global.generate('string'),
        owner: global.generate('string'),
        justice_procedure: global.generate('string'),
        justice_rendered: global.generate('string'),
        justice_rendered_by: global.generate('string'),
        justice_rendered_at: global.generate('string'),
        justice_challenged: global.generate('string'),
        police_status: global.generate('string'),
        police_requested_at: global.generate('string'),
        police_granted_at: global.generate('string'),
        bailiff: global.generate('string'),

        living_conditions_version: 2,
        water_access_type: 'autre',
        water_access_type_details: 'comment',
        water_access_is_public: false,
        water_access_is_continuous: false,
        water_access_is_continuous_details: 'comment',
        water_access_is_local: true,
        water_access_is_close: true,
        water_access_is_unequal: true,
        water_access_is_unequal_details: 'comment',
        water_access_has_stagnant_water: true,
        water_access_comments: 'comment',

        sanitary_open_air_defecation: true,
        sanitary_toilet_types: ['latrines', 'toilettes_chimiques'],
        sanitary_access_working_toilets: true,
        sanitary_access_toilets_are_inside: true,
        sanitary_access_toilets_are_lighted: true,
        sanitary_access_hand_washing: true,

        electricity_access: true,
        electricity_access_is_unequal: true,
        electricity_access_types: ['electrogene', 'reseau_urbain', 'installation_du_bati'],

        trash_is_piling: true,
        trash_evacuation_is_close: true,
        trash_evacuation_is_safe: true,
        trash_evacuation_is_regular: true,
        trash_bulky_is_piling: true,

        pest_animals: true,
        pest_animals_details: 'comment',

        fire_prevention: true,
    };
}

export function serialized(location: City = defaultLocation, override = {}): Shantytown {
    const {
        city, epci, departement, region,
    } = location;

    const shantytown: Shantytown = {
        type: 'shantytown',
        id: 1,
        updatedWithoutAnyChange: false,
        city: {
            ...city,
            latitude: 0,
            longitude: 1,
        },
        epci,
        departement: {
            ...departement,
            latitude: 0,
            longitude: 1,
            chieftown: {
                code: '10',
                name: '10',
                latitude: 0,
                longitude: 1,
            },
        },
        region: {
            ...region,
            latitude: 0,
            longitude: 1,
            chieftown: {
                code: '10',
                name: '10',
                latitude: 0,
                longitude: 1,
            },
        },
        name: null,
        status: 'open',
        closingContext: null,
        latitude: 1,
        longitude: 0,
        declaredAt: null,
        builtAt: Date.now(),
        isReinstallation: false,
        reinstallationComments: null,
        reinstallationIncomingTowns: [],
        closedAt: null,
        address: 'adresse',
        addressDetails: null,
        addressSimple: 'Adresse',
        attachments: [],
        usename: 'Nom',
        populationTotal: null,
        populationTotalFemales: null,
        populationMinorsGirls: null,
        populationCouples: null,
        populationMinors: null,
        populationMinors0To3: null,
        populationMinors3To6: null,
        populationMinors6To12: null,
        populationMinors12To16: null,
        populationMinors16To18: null,
        minorsInSchool: null,
        caravans: null,
        huts: null,
        tents: null,
        cars: null,
        mattresses: null,
        livingConditions: {
            version: 2,
            electricity: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: ['access', 'acces_types', 'access_is_unequal'],
                },
                access: null,
                access_types: [],
                access_is_unequal: null,
            },
            water: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: [
                        'access_type',
                        'access_type_details',
                        'access_is_public',
                        'access_is_continuous',
                        'access_is_continuous_details',
                        'access_is_local',
                        'access_is_close',
                        'access_is_unequal',
                        'access_is_unequal_details',
                        'access_has_stagnant_water',
                        'access_comments',
                    ],
                },
                access_type: null,
                access_type_details: null,
                access_is_public: null,
                access_is_continuous: null,
                access_is_continuous_details: null,
                access_is_local: null,
                access_is_close: null,
                access_is_unequal: null,
                access_is_unequal_details: null,
                access_has_stagnant_water: null,
                access_comments: null,
            },
            trash: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: [
                        'is_piling',
                        'evacuation_is_close',
                        'evacuation_is_safe',
                        'evacuation_is_regular',
                        'bulky_is_piling',
                    ],
                },
                is_piling: null,
                evacuation_is_close: null,
                evacuation_is_safe: null,
                evacuation_is_regular: null,
                bulky_is_piling: null,
            },
            sanitary: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: [
                        'open_air_defecation',
                        'working_toilets',
                        'toilet_types',
                        'toilets_are_inside',
                        'toilets_are_lighted',
                        'hand_washing',
                    ],
                },
                open_air_defecation: null,
                working_toilets: null,
                toilet_types: [],
                toilets_are_inside: null,
                toilets_are_lighted: null,
                hand_washing: null,
            },
            pest_animals: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: ['presence', 'details'],
                },
                presence: null,
                details: null,
            },
            fire_prevention: {
                status: {
                    status: 'unknown',
                    positive: [],
                    negative: [],
                    unknown: ['diagnostic'],
                },
                diagnostic: null,
            },
        },
        censusStatus: 'none',
        censusConductedBy: null,
        censusConductedAt: null,
        fieldType: {
            id: 1,
            label: 'Inconnu',
        },
        ownerType: {
            id: 1,
            label: 'Inconnu',
        },
        socialOrigins: [],
        comments: [],
        actors: [],
        actions: [],
        closingSolutions: [],
        closedWithSolutions: null,
        changelog: [],
        createdAt: Date.now(),
        updatedAt: null,
        createdBy: fakeUser(),
        updatedBy: fakeUser(),
        heatwaveStatus: false,
        resorptionTarget: null,
        completionRate: 0.5,
        distance: null,
        preparatoryPhasesTowardResorption: null,
    };

    return {
        ...shantytown,
        ...override,
    };
}

export default serialized;
