export type ShantytownLivingConditionsRawData = {
    waterAccessType: string,
    waterAccessIsPublic: boolean | null,
    waterAccessIsContinuous: boolean | null,
    waterAccessIsLocal: boolean | null,
    waterAccessIsClose: boolean | null,
    waterAccessIsUnequal: boolean | null,
    waterAccessHasStagnantWater: boolean | null,
    toiletTypes: string[],
    sanitaryAccessOpenAirDefecation: boolean | null,
    sanitaryAccessWorkingToilets: boolean | null,
    sanitaryAccessToiletsAreInside: boolean | null,
    sanitaryAccessToiletsAreLighted: boolean | null,
    sanitaryAccessHandWashing: boolean | null,
    electricityAccess: boolean | null,
    electricityAccessTypes: string[],
    electricityAccessIsUnequal: boolean | null,
    trashIsPiling: boolean | null,
    trashEvacuationIsClose: boolean | null,
    trashEvacuationIsSafe: boolean | null,
    trashEvacuationIsRegular: boolean | null,
    trashBulkyIsPiling: boolean | null,
    pestAnimals: boolean | null,
    firePrevention: boolean | null,
};
