export default {
    categories: [
        { value: "caracteristics", label: "Caractéristiques" },
        { value: "people", label: "Habitants" },
        { value: "living_conditions", label: "Conditions de vie" },
        { value: "procedure", label: "Procédures" },
    ],
    fields: {
        caracteristics: [
            "builtAt",
            "declaredAt",
            "addressDetails",
            "addressSimple",
            "fieldType",
            "owner_type",
        ],
        people: [
            "isReinstallation",
            "reinstallationComments",
            "censusStatus",
            "populationTotal",
            "populationTotalFemales",
            "populationCouples",
            "populationMinors",
            "populationMinorsGirls",
            "populationMinors0To3",
            "populationMinors3To6",
            "populationMinors6To12",
            "populationMinors12To16",
            "populationMinors16To18",
            "minorsInSchool",
            "caravans",
            "huts",
            "tents",
            "cars",
            "mattresses",
            "socialOrigins",
        ],
        living_conditions: [
            // v2
            "livingConditions.version",
            "livingConditions.water.access_type",
            "livingConditions.water.access_type_details",
            "livingConditions.water.access_is_public",
            "livingConditions.water.access_is_continuous",
            "livingConditions.water.access_is_continuous_details",
            "livingConditions.water.access_is_local",
            "livingConditions.water.access_is_close",
            "livingConditions.water.access_is_unequal",
            "livingConditions.water.access_is_unequal_details",
            "livingConditions.water.access_has_stagnant_water",
            "livingConditions.water.access_comments",
            "livingConditions.sanitary.working_toilets",
            "livingConditions.sanitary.open_air_defecation",
            "livingConditions.sanitary.toilet_types",
            "livingConditions.sanitary.toilets_are_inside",
            "livingConditions.sanitary.toilets_are_lighted",
            "livingConditions.sanitary.hand_washing",
            "livingConditions.electricity.access",
            "livingConditions.electricity.access_types",
            "livingConditions.electricity.access_is_unequal",
            "livingConditions.trash.is_piling",
            "livingConditions.trash.evacuation_is_close",
            "livingConditions.trash.evacuation_is_safe",
            "livingConditions.trash.evacuation_is_regular",
            "livingConditions.trash.bulky_is_piling",
            "livingConditions.pest_animals.presence",
            "livingConditions.pest_animals.details",
            "livingConditions.fire_prevention.diagnostic",
            // v1
            "livingConditions.electricity.type",
            "livingConditions.electricity.comments",
            "livingConditions.water.access",
            "livingConditions.water.comments",
            "livingConditions.water.potable",
            "livingConditions.water.continuousAccess",
            "livingConditions.water.publicPoint",
            "livingConditions.water.distance",
            "livingConditions.water.roadsToCross",
            "livingConditions.water.everyoneHasAccess",
            "livingConditions.water.stagnantWater",
            "livingConditions.water.handWashAccess",
            "livingConditions.water.handWashAccessNumber",
            "livingConditions.sanitary.access",
            "livingConditions.sanitary.comments",
            "livingConditions.sanitary.number",
            "livingConditions.sanitary.insalubrious",
            "livingConditions.sanitary.onSite",
            "livingConditions.trash.evacuation",
            "livingConditions.trash.cansOnSite",
            "livingConditions.trash.accumulation",
            "livingConditions.trash.evacuationRegular",
            "livingConditions.vermin.vermin",
            "livingConditions.vermin.comments",
            "livingConditions.firePrevention.measures",
            "livingConditions.firePrevention.diagnostic",
            "livingConditions.firePrevention.siteAccessible",
            "livingConditions.firePrevention.devices",
            "livingConditions.firePrevention.comments",
        ],

        procedure: [
            "ownerComplaint",
            "justiceChallenged",
            "justiceProcedure",
            "justiceRendered",
            "justiceRenderedAt",
            "justiceRenderedBy",
            "policeStatus",
            "policeRequestedAt",
            "policeGrantedAt",
            "bailiff",
            "existingLitigation",
            "evacuationUnderTimeLimit",
            "administrativeOrderDecisionAt",
            "administrativeOrderDecisionRenderedBy",
            "administrativeOrderEvacuationAt",
            "insalubrityOrder",
            "insalubrityOrderDisplayed",
            "insalubrityOrderType",
            "insalubrityOrderBy",
            "insalubrityOrderAt",
            "insalubrityParcels",
        ],
    },
};
