export default {
    categories: [
        { value: "caracteristics", label: "Caractéristiques" },
        { value: "people", label: "Habitants" },
        { value: "living_conditions", label: "Conditions de vie" },
        { value: "justice", label: "Procédure judiciaire" },
    ],
    fields: {
        caracteristics: [
            "builtAt",
            "declaredAt",
            "addressDetails",
            "addressSimple",
            "fieldType",
            "owner_type",
        ],
        people: [
            "isReinstallation",
            "reinstallationComments",
            "censusStatus",
            "populationTotal",
            "populationCouples",
            "populationMinors",
            "populationMinors0To3",
            "populationMinors3To6",
            "populationMinors6To12",
            "populationMinors12To16",
            "populationMinors16To18",
            "minorsInSchool",
            "caravans",
            "huts",
            "socialOrigins",
        ],
        living_conditions: [
            // new version v2
            "livingConditions.version",
            "livingConditions.water.access_type",
            "livingConditions.water.access_type_details",
            "livingConditions.water.access_is_public",
            "livingConditions.water.access_is_continuous",
            "livingConditions.water.access_is_continuous_details",
            "livingConditions.water.access_is_local",
            "livingConditions.water.access_is_close",
            "livingConditions.water.access_is_unequal",
            "livingConditions.water.access_is_unequal_details",
            "livingConditions.water.access_has_stagnant_water",
            "livingConditions.water.access_comments",
            "livingConditions.sanitary.working_toilets",
            "livingConditions.sanitary.open_air_defecation",
            "livingConditions.sanitary.toilet_types",
            "livingConditions.sanitary.toilets_are_inside",
            "livingConditions.sanitary.toilets_are_lighted",
            "livingConditions.sanitary.hand_washing",
            "livingConditions.electricity.access",
            "livingConditions.electricity.access_types",
            "livingConditions.electricity.access_is_unequal",
            "livingConditions.trash.is_piling",
            "livingConditions.trash.evacuation_is_close",
            "livingConditions.trash.evacuation_is_safe",
            "livingConditions.trash.evacuation_is_regular",
            "livingConditions.trash.bulky_is_piling",
            "livingConditions.pest_animals.presence",
            "livingConditions.pest_animals.details",
            "livingConditions.fire_prevention.diagnostic",
        ],

        justice: [
            "ownerComplaint",
            "justiceChallenged",
            "justiceProcedure",
            "justiceRendered",
            "justiceRenderedAt",
            "justiceRenderedBy",
            "policeStatus",
            "policeRequestedAt",
            "policeGrantedAt",
            "bailiff",
        ],
    },
};
