import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faTwitterSquare,
    faFacebookSquare
} from "@fortawesome/free-brands-svg-icons";
import {
    faFlag,
    faPaperPlane,
    faUnlink,
    faUser,
    faUserCheck,
    faUserShield,
    faArrowRight,
    faEye,
    faEyeSlash,
    faPencilAlt,
    faTimes,
    faMapMarkedAlt,
    faChartLine,
    faComments,
    faEnvelope,
    faPlayCircle,
    faFileExcel,
    faSortDown,
    faCaretSquareLeft,
    faCaretSquareRight,
    faCaretUp,
    faCaretDown,
    faComment,
    faTrashAlt,
    faHistory,
    faMapPin,
    faFilePdf,
    faUsers,
    faUserPlus,
    faFileDownload,
    faAddressBook,
    faSync,
    faInfoCircle,
    faList,
    faTable,
    faBookReader,
    faEuroSign,
    faPlusCircle,
    faIdCard,
    faUserMd,
    faBriefcase,
    faHome,
    faSeedling,
    faQuestion,
    faTint,
    faTintSlash,
    faHandHoldingMedical,
    faMapMarkerAlt,
    faBook,
    faFileSignature,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faSpinner,
    faArrowLeft,
    faSearch
} from "@fortawesome/free-solid-svg-icons";

library.add(faFlag);
library.add(faChevronDown);
library.add(faPaperPlane);
library.add(faUnlink);
library.add(faUser);
library.add(faUserCheck);
library.add(faUserShield);
library.add(faArrowRight);
library.add(faEye);
library.add(faEyeSlash);
library.add(faPencilAlt);
library.add(faTimes);
library.add(faMapMarkedAlt);
library.add(faChartLine);
library.add(faComments);
library.add(faEnvelope);
library.add(faPlayCircle);
library.add(faFileExcel);
library.add(faSortDown);
library.add(faCaretSquareLeft);
library.add(faCaretSquareRight);
library.add(faCaretUp);
library.add(faCaretDown);
library.add(faComment);
library.add(faTrashAlt);
library.add(faHistory);
library.add(faMapPin);
library.add(faFilePdf);
library.add(faUsers);
library.add(faUserPlus);
library.add(faFileDownload);
library.add(faAddressBook);
library.add(faSync);
library.add(faInfoCircle);
library.add(faList);
library.add(faTable);
library.add(faBookReader);
library.add(faEuroSign);
library.add(faPlusCircle);
library.add(faIdCard);
library.add(faUserMd);
library.add(faBriefcase);
library.add(faHome);
library.add(faSeedling);
library.add(faQuestion);
library.add(faTint);
library.add(faTintSlash);
library.add(faHandHoldingMedical);
library.add(faMapMarkerAlt);
library.add(faBook);
library.add(faFileSignature);
library.add(faChevronLeft);
library.add(faChevronRight);
library.add(faArrowLeft);
library.add(faArrowRight);
library.add(faSpinner);
library.add(faTwitterSquare);
library.add(faFacebookSquare);
library.add(faSearch);
