// This module cannot be lazyloaded as it's defined in src/App.vue
import notifications from "vue-notification/dist/ssr";
import NotificationsGroup from "./NotificationsGroup.vue";
import registerVeeValidate from "./registerVeeValidate";

// Lazyloaded modules
const Accordion = () => import("./Accordion");
const AccordionItem = () => import("./AccordionItem");
const Button = () => import("./Button");
const TextInput = () => import("./Form/input/TextInput.vue");
const PasswordInput = () => import("./Form/input/PasswordInput.vue");
const InlineTextInput = () => import("./Form/input/InlineTextInput.vue");
const TextArea = () => import("./Form/input/TextArea.vue");
const Icon = () => import("./Icon.vue");
const Checkbox = () => import("./Form/input/Checkbox.vue");
const Radio = () => import("./Form/input/Radio.vue");
const Select = () => import("./Form/input/Select.vue");
const SelectOption = () => import("./Form/input/SelectOption.vue");
const FormGroup = () => import("./Form/FormGroup.vue");
const InputGroup = () => import("./Form/InputGroup.vue");
const MandatoryStar = () => import("./Form/utils/MandatoryStar.vue");
const FormParagraph = () => import("./Form/FormParagraph.vue");
const Menu = () => import("./Menu/Menu.vue");
const MenuItem = () => import("./Menu/MenuItem.vue");
const Dropdown = () => import("./Dropdown.vue");
const CustomFilter = () => import("./Filter.vue");
const FullBottomSection = () => import("./FullBottomSection.vue");
const Modal = () => import("./Modal.vue");
const Callout = () => import("./Callout.vue");
const SidePanel = () => import("./SidePanel.vue");
const Sort = () => import("./Sort.vue");
const Autocomplete = () => import("./Autocomplete.vue");
const Spinner = () => import("./Spinner.vue");
const CheckableGroup = () => import("./Form/CheckableGroup.vue");
const Datepicker = () => import("./Datepicker.vue");
const Tag = () => import("./Tag.vue");
const Pagination = () => import("./Pagination.vue");
const PanelInfo = () => import("./PanelInfo.vue");
const Link = () => import("./Link.vue");
const MapV2 = () => import("./Map.vue");
const InfoBanner = () => import("./InfoBanner.vue");
const Tooltip = () => import("./Tooltip.vue");
const AutocompleteVue = () => import("@trevoreyre/autocomplete-vue");
const HeaderTab = () => import("./HeaderTab.vue");
export default function(vueInstance) {
    vueInstance.component("Button", Button);
    vueInstance.component("TextInput", TextInput);
    vueInstance.component("PasswordInput", PasswordInput);
    vueInstance.component("InlineTextInput", InlineTextInput);
    vueInstance.component("TextArea", TextArea);
    vueInstance.component("Icon", Icon);
    vueInstance.component("Menu", Menu);
    vueInstance.component("MenuItem", MenuItem);
    vueInstance.component("Checkbox", Checkbox);
    vueInstance.component("Radio", Radio);
    vueInstance.component("Select", Select);
    vueInstance.component("SelectOption", SelectOption);
    vueInstance.component("FormGroup", FormGroup);
    vueInstance.component("MandatoryStar", MandatoryStar);
    vueInstance.component("Dropdown", Dropdown);
    vueInstance.component("CustomFilter", CustomFilter);
    vueInstance.component("FullBottomSection", FullBottomSection);
    vueInstance.component("Modal", Modal);
    vueInstance.component("SidePanel", SidePanel);
    vueInstance.component("Sort", Sort);
    vueInstance.component("CheckableGroup", CheckableGroup);
    vueInstance.component("InputGroup", InputGroup);
    vueInstance.component("FormParagraph", FormParagraph);
    vueInstance.component("Callout", Callout);
    vueInstance.component("Spinner", Spinner);
    vueInstance.component("AutocompleteV2", Autocomplete);
    vueInstance.component("DatepickerV2", Datepicker);
    vueInstance.component("Tag", Tag);
    vueInstance.component("Pagination", Pagination);
    vueInstance.component("PanelInfo", PanelInfo);
    vueInstance.component("Link", Link);
    vueInstance.component("MapV2", MapV2);
    vueInstance.component("InfoBanner", InfoBanner);
    vueInstance.component("Tooltip", Tooltip);
    vueInstance.component("Accordion", Accordion);
    vueInstance.component("AccordionItem", AccordionItem);
    vueInstance.component("HeaderTab", HeaderTab);

    vueInstance.use(notifications);
    vueInstance.component("NotificationsGroup", NotificationsGroup);
    vueInstance.component("AutocompleteVue", AutocompleteVue);

    registerVeeValidate(vueInstance);
}
