<template>
    <section>
        <p class="mt-3 flex flex-col">
            <TextInput
                variant="filter"
                width="w-32"
                id="population_total"
                name="population_total"
                :label="labels.population_total"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_couples"
                name="population_couples"
                :label="labels.population_couples"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors"
                name="population_minors"
                :label="labels.population_minors"
            />

            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors_0_3"
                name="population_minors_0_3"
                :label="labels.population_minors_0_3"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors_3_6"
                name="population_minors_3_6"
                :label="labels.population_minors_3_6"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors_6_12"
                name="population_minors_6_12"
                :label="labels.population_minors_6_12"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors_12_16"
                name="population_minors_12_16"
                :label="labels.population_minors_12_16"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="population_minors_16_18"
                name="population_minors_16_18"
                :label="labels.population_minors_16_18"
            />
            <TextInput
                variant="filter"
                width="w-32"
                id="minors_in_school"
                name="minors_in_school"
                :label="labels.minors_in_school"
            />
            <TextInput
                variant="filter"
                id="caravans"
                name="caravans"
                :label="labels.caravans"
                width="w-32"
            />
            <TextInput
                variant="filter"
                id="huts"
                name="huts"
                :label="labels.huts"
                width="w-32"
            />
            <TextInput
                variant="filter"
                id="tents"
                name="tents"
                :label="labels.tents"
                width="w-32"
            />
            <TextInput
                variant="filter"
                id="cars"
                name="cars"
                :label="labels.cars"
                width="w-32"
            />
            <TextInput
                variant="filter"
                id="mattresses"
                name="mattresses"
                :label="labels.mattresses"
                width="w-32"
            />
        </p>
    </section>
</template>

<script setup>
import labels from "../FormMiseAJourDeSiteSectionHabitants.labels";

import { TextInput } from "@resorptionbidonvilles/ui";
</script>
