import { QueryTypes, Transaction } from 'sequelize';
import { sequelize } from '#db/sequelize';
import { ActionInput } from '#server/services/action/ActionInput.d';

export default (actionId: number, authorId: number, date: Date, data: ActionInput, transaction: Transaction) => sequelize.query(
    `INSERT INTO action_metrics(
        fk_action,
        date,
        nombre_personnes,
        nombre_menages,
        nombre_femmes,
        nombre_mineurs,
        sante_nombre_personnes,
        travail_nombre_personnes,
        travail_nombre_femmes,
        hebergement_nombre_personnes,
        hebergement_nombre_menages,
        logement_nombre_personnes,
        logement_nombre_menages,
        scolaire_mineurs_scolarisables,
        scolaire_mineurs_en_mediation,
        scolaire_nombre_maternelle,
        scolaire_nombre_elementaire,
        scolaire_nombre_college,
        scolaire_nombre_lycee,
        scolaire_nombre_autre,
        created_by
    ) VALUES (
        :action_id,
        :date,
        :nombre_personnes,
        :nombre_menages,
        :nombre_femmes,
        :nombre_mineurs,
        :sante_nombre_personnes,
        :travail_nombre_personnes,
        :travail_nombre_femmes,
        :hebergement_nombre_personnes,
        :hebergement_nombre_menages,
        :logement_nombre_personnes,
        :logement_nombre_menages,
        :scolaire_mineurs_scolarisables,
        :scolaire_mineurs_en_mediation,
        :scolaire_nombre_maternelle,
        :scolaire_nombre_elementaire,
        :scolaire_nombre_college,
        :scolaire_nombre_lycee,
        :scolaire_nombre_autre,
        :author_id
    )`,
    {
        type: QueryTypes.INSERT,
        transaction,
        replacements: {
            nombre_personnes: data.nombre_personnes,
            nombre_menages: data.nombre_menages,
            nombre_femmes: data.nombre_femmes,
            nombre_mineurs: data.nombre_mineurs,
            sante_nombre_personnes: data.sante_nombre_personnes,
            travail_nombre_personnes: data.travail_nombre_personnes,
            travail_nombre_femmes: data.travail_nombre_femmes,
            hebergement_nombre_personnes: data.hebergement_nombre_personnes,
            hebergement_nombre_menages: data.hebergement_nombre_menages,
            logement_nombre_personnes: data.logement_nombre_personnes,
            logement_nombre_menages: data.logement_nombre_menages,
            scolaire_mineurs_scolarisables: data.scolaire_mineurs_scolarisables,
            scolaire_mineurs_en_mediation: data.scolaire_mineurs_en_mediation,
            scolaire_nombre_maternelle: data.scolaire_nombre_maternelle,
            scolaire_nombre_elementaire: data.scolaire_nombre_elementaire,
            scolaire_nombre_college: data.scolaire_nombre_college,
            scolaire_nombre_lycee: data.scolaire_nombre_lycee,
            scolaire_nombre_autre: data.scolaire_nombre_autre,
            author_id: authorId,
            date,
            action_id: actionId,
        },
    },
);
