const sequelize = require('#db/sequelize');

module.exports = async (townData) => {
    const result = await sequelize.query(
        `INSERT INTO shantytowns(
            status,
            latitude,
            longitude,
            address,
            address_details,
            fk_city,
            built_at,
            fk_field_type,
            fk_owner_type,
            population_total,
            population_couples,
            population_minors,
            created_by,
            owner,
            declared_at,
            census_status,
            census_conducted_at,
            census_conducted_by,
            justice_rendered_by,
            justice_rendered_at,
            police_status,
            police_requested_at,
            police_granted_at,
            bailiff,
            justice_procedure,
            justice_rendered,
            justice_challenged,
            owner_complaint,
            name,
            population_minors_0_3,
            population_minors_3_6,
            population_minors_6_12,
            population_minors_12_16,
            population_minors_16_18,
            minors_in_school,
            is_reinstallation,
            reinstallation_comments
        ) VALUES (
            'open',
            :latitude,
            :longitude,
            :address,
            :address_details,
            :fk_city,
            :built_at,
            :fk_field_type,
            :fk_owner_type,
            :population_total,
            :population_couples,
            :population_minors,
            :created_by,
            :owner,
            :declared_at,
            :census_status,
            :census_conducted_at,
            :census_conducted_by,
            :justice_rendered_by,
            :justice_rendered_at,
            :police_status,
            :police_requested_at,
            :police_granted_at,
            :bailiff,
            :justice_procedure,
            :justice_rendered,
            :justice_challenged,
            :owner_complaint,
            :name,
            :population_minors_0_3,
            :population_minors_3_6,
            :population_minors_6_12,
            :population_minors_12_16,
            :population_minors_16_18,
            :minors_in_school,
            :is_reinstallation,
            :reinstallation_comments
        ) RETURNING shantytown_id AS id`, {
            replacements: {
                latitude: townData.latitude,
                longitude: townData.longitude,
                address: townData.address,
                address_details: townData.addressDetails || null,
                fk_city: townData.city,
                built_at: townData.builtAt || null,
                fk_field_type: townData.fieldType,
                fk_owner_type: townData.ownerType,
                population_total: townData.populationTotal || null,
                population_couples: townData.populationCouples || null,
                population_minors: townData.populationMinors || null,
                created_by: townData.createdBy,
                owner: townData.owner || null,
                declared_at: townData.declaredAt || null,
                census_status: townData.censusStatus || null,
                census_conducted_at: townData.censusConductedAt || null,
                census_conducted_by: townData.censusConductedBy || null,
                justice_rendered_by: townData.justiceRenderedBy || null,
                justice_rendered_at: townData.justiceRenderedAt || null,
                police_status: townData.policeStatus || null,
                police_requested_at: townData.policeRequestedAt || null,
                police_granted_at: townData.policeGrantedAt || null,
                bailiff: townData.bailiff || null,
                justice_procedure: townData.justiceProcedure || null,
                justice_rendered: townData.justiceRendered || null,
                justice_challenged: townData.justiceChallenged || null,
                owner_complaint: townData.ownerComplaint || null,
                name: townData.name || null,
                population_minors_0_3: townData.populationMinors0To3 || null,
                population_minors_3_6: townData.populationMinors3To6 || null,
                population_minors_6_12: townData.populationMinors6To12 || null,
                population_minors_12_16: townData.populationMinors12To16 || null,
                population_minors_16_18: townData.populationMinors16To18 || null,
                minors_in_school: townData.minorsInSchool || null,
                is_reinstallation: townData.isReinstallation || null,
                reinstallation_comments: townData.reinstallationComments || null,
            },
        },
    );

    return result[0][0].id;
};
