import { sequelize } from '#db/sequelize';

export default async (townData, transaction = undefined) => {
    const result = await sequelize.query(
        `INSERT INTO shantytowns(
            ${townData.id ? 'shantytown_id,' : ''}
            status,
            latitude,
            longitude,
            address,
            address_details,
            fk_city,
            built_at,
            fk_field_type,
            fk_owner_type,
            population_total,
            population_couples,
            population_minors,
            created_by,
            owner,
            declared_at,
            census_status,
            census_conducted_at,
            census_conducted_by,
            justice_rendered_by,
            justice_rendered_at,
            police_status,
            police_requested_at,
            police_granted_at,
            bailiff,
            justice_procedure,
            justice_rendered,
            justice_challenged,
            owner_complaint,
            name,
            population_total_females,
            population_minors_girls,
            population_minors_0_3,
            population_minors_3_6,
            population_minors_6_12,
            population_minors_12_16,
            population_minors_16_18,
            minors_in_school,
            caravans,
            huts,
            tents,
            cars,
            mattresses,
            is_reinstallation,
            reinstallation_comments,
            living_conditions_version,
            water_access_type,
            water_access_type_details,
            water_access_is_public,
            water_access_is_continuous,
            water_access_is_continuous_details,
            water_access_is_local,
            water_access_is_close,
            water_access_is_unequal,
            water_access_is_unequal_details,
            water_access_has_stagnant_water,
            water_access_comments,
            sanitary_access_open_air_defecation,
            sanitary_access_working_toilets,
            sanitary_access_toilets_are_inside,
            sanitary_access_toilets_are_lighted,
            sanitary_access_hand_washing,
            electricity_access,
            electricity_access_is_unequal,
            trash_is_piling,
            trash_evacuation_is_close,
            trash_evacuation_is_safe,
            trash_evacuation_is_regular,
            trash_bulky_is_piling,
            pest_animals,
            pest_animals_details,
            fire_prevention
        ) VALUES (
            ${townData.id ? ':id,' : ''}
            'open',
            :latitude,
            :longitude,
            :address,
            :address_details,
            :fk_city,
            :built_at,
            :fk_field_type,
            :fk_owner_type,
            :population_total,
            :population_couples,
            :population_minors,
            :created_by,
            :owner,
            :declared_at,
            :census_status,
            :census_conducted_at,
            :census_conducted_by,
            :justice_rendered_by,
            :justice_rendered_at,
            :police_status,
            :police_requested_at,
            :police_granted_at,
            :bailiff,
            :justice_procedure,
            :justice_rendered,
            :justice_challenged,
            :owner_complaint,
            :name,
            :population_total_females,
            :population_minors_girls,
            :population_minors_0_3,
            :population_minors_3_6,
            :population_minors_6_12,
            :population_minors_12_16,
            :population_minors_16_18,
            :minors_in_school,
            :caravans,
            :huts,
            :tents,
            :cars,
            :mattresses,
            :is_reinstallation,
            :reinstallation_comments,
            :living_conditions_version,
            :water_access_type,
            :water_access_type_details,
            :water_access_is_public,
            :water_access_is_continuous,
            :water_access_is_continuous_details,
            :water_access_is_local,
            :water_access_is_close,
            :water_access_is_unequal,
            :water_access_is_unequal_details,
            :water_access_has_stagnant_water,
            :water_access_comments,
            :sanitary_open_air_defecation,
            :sanitary_access_working_toilets,
            :sanitary_access_toilets_are_inside,
            :sanitary_access_toilets_are_lighted,
            :sanitary_access_hand_washing,
            :electricity_access,
            :electricity_access_is_unequal,
            :trash_is_piling,
            :trash_evacuation_is_close,
            :trash_evacuation_is_safe,
            :trash_evacuation_is_regular,
            :trash_bulky_is_piling,
            :pest_animals,
            :pest_animals_details,
            :fire_prevention
        ) RETURNING shantytown_id AS id`, {
            transaction,
            replacements: {
                id: townData.id,
                latitude: townData.latitude,
                longitude: townData.longitude,
                address: townData.address,
                address_details: townData.addressDetails || null,
                fk_city: townData.city,
                built_at: townData.builtAt || null,
                fk_field_type: townData.fieldType,
                fk_owner_type: townData.ownerType,
                population_total: townData.populationTotal || null,
                population_couples: townData.populationCouples || null,
                population_minors: townData.populationMinors || null,
                caravans: townData.caravans || null,
                huts: townData.huts || null,
                tents: townData.tents || null,
                cars: townData.cars || null,
                mattresses: townData.mattresses || null,
                created_by: townData.createdBy,
                owner: townData.owner || null,
                declared_at: townData.declaredAt || null,
                census_status: townData.censusStatus || null,
                census_conducted_at: townData.censusConductedAt || null,
                census_conducted_by: townData.censusConductedBy || null,
                justice_rendered_by: townData.justiceRenderedBy || null,
                justice_rendered_at: townData.justiceRenderedAt || null,
                police_status: townData.policeStatus || null,
                police_requested_at: townData.policeRequestedAt || null,
                police_granted_at: townData.policeGrantedAt || null,
                bailiff: townData.bailiff || null,
                justice_procedure: townData.justiceProcedure || null,
                justice_rendered: townData.justiceRendered || null,
                justice_challenged: townData.justiceChallenged || null,
                owner_complaint: townData.ownerComplaint || null,
                name: townData.name || null,
                population_total_females: townData.populationTotalFemales || null,
                population_minors_girls: townData.populationMinorsGirls || null,
                population_minors_0_3: townData.populationMinors0To3 || null,
                population_minors_3_6: townData.populationMinors3To6 || null,
                population_minors_6_12: townData.populationMinors6To12 || null,
                population_minors_12_16: townData.populationMinors12To16 || null,
                population_minors_16_18: townData.populationMinors16To18 || null,
                minors_in_school: townData.minorsInSchool || null,
                is_reinstallation: townData.isReinstallation || null,
                reinstallation_comments: townData.reinstallationComments || null,
                living_conditions_version: townData.living_conditions_version || undefined,
                water_access_type: townData.water_access_type || null,
                water_access_type_details: townData.water_access_type_details || null,
                water_access_is_public: typeof townData.water_access_is_public === 'boolean' ? townData.water_access_is_public : null,
                water_access_is_continuous: typeof townData.water_access_is_continuous === 'boolean' ? townData.water_access_is_continuous : null,
                water_access_is_continuous_details: townData.water_access_is_continuous_details || null,
                water_access_is_local: typeof townData.water_access_is_local === 'boolean' ? townData.water_access_is_local : null,
                water_access_is_close: typeof townData.water_access_is_close === 'boolean' ? townData.water_access_is_close : null,
                water_access_is_unequal: typeof townData.water_access_is_unequal === 'boolean' ? townData.water_access_is_unequal : null,
                water_access_is_unequal_details: townData.water_access_is_unequal_details || null,
                water_access_has_stagnant_water: typeof townData.water_access_has_stagnant_water === 'boolean' ? townData.water_access_has_stagnant_water : null,
                water_access_comments: townData.water_access_comments || null,
                sanitary_open_air_defecation: typeof townData.sanitary_open_air_defecation === 'boolean' ? townData.sanitary_open_air_defecation : null,
                sanitary_access_working_toilets: typeof townData.sanitary_access_working_toilets === 'boolean' ? townData.sanitary_access_working_toilets : null,
                sanitary_access_toilets_are_inside: typeof townData.sanitary_access_toilets_are_inside === 'boolean' ? townData.sanitary_access_toilets_are_inside : null,
                sanitary_access_toilets_are_lighted: typeof townData.sanitary_access_toilets_are_lighted === 'boolean' ? townData.sanitary_access_toilets_are_lighted : null,
                sanitary_access_hand_washing: typeof townData.sanitary_access_hand_washing === 'boolean' ? townData.sanitary_access_hand_washing : null,
                electricity_access: townData.electricity_access || null,
                electricity_access_is_unequal: typeof townData.electricity_access_is_unequal === 'boolean' ? townData.electricity_access_is_unequal : null,
                trash_is_piling: typeof townData.trash_is_piling === 'boolean' ? townData.trash_is_piling : null,
                trash_evacuation_is_close: typeof townData.trash_evacuation_is_close === 'boolean' ? townData.trash_evacuation_is_close : null,
                trash_evacuation_is_safe: typeof townData.trash_evacuation_is_safe === 'boolean' ? townData.trash_evacuation_is_safe : null,
                trash_evacuation_is_regular: typeof townData.trash_evacuation_is_regular === 'boolean' ? townData.trash_evacuation_is_regular : null,
                trash_bulky_is_piling: typeof townData.trash_bulky_is_piling === 'boolean' ? townData.trash_bulky_is_piling : null,
                pest_animals: typeof townData.pest_animals === 'boolean' ? townData.pest_animals : null,
                pest_animals_details: townData.pest_animals_details || null,
                fire_prevention: typeof townData.fire_prevention === 'boolean' ? townData.fire_prevention : null,
            },
        },
    );
    const createdTown: any = result[0][0];
    return createdTown.id;
};
