import { sequelize } from '#db/sequelize';

export default async (townData, transaction = undefined) => {
    const result = await sequelize.query(
        `INSERT INTO shantytowns(
            status,
            latitude,
            longitude,
            address,
            address_details,
            fk_city,
            built_at,
            fk_field_type,
            fk_owner_type,
            population_total,
            population_couples,
            population_minors,
            access_to_water,
            trash_evacuation,
            created_by,
            owner,
            declared_at,
            census_status,
            census_conducted_at,
            census_conducted_by,
            justice_rendered_by,
            justice_rendered_at,
            police_status,
            police_requested_at,
            police_granted_at,
            bailiff,
            justice_procedure,
            justice_rendered,
            justice_challenged,
            owner_complaint,
            fk_electricity_type,
            water_comments,
            electricity_comments,
            sanitary_comments,
            access_to_sanitary,
            name,
            population_minors_0_3,
            population_minors_3_6,
            population_minors_6_12,
            population_minors_12_16,
            population_minors_16_18,
            minors_in_school,
            water_potable,
            water_continuous_access,
            water_public_point,
            water_distance,
            water_roads_to_cross,
            water_everyone_has_access,
            water_stagnant_water,
            water_hand_wash_access,
            water_hand_wash_access_number,
            sanitary_number,
            sanitary_insalubrious,
            sanitary_on_site,
            trash_cans_on_site,
            trash_accumulation,
            trash_evacuation_regular,
            vermin,
            vermin_comments,
            fire_prevention_measures,
            fire_prevention_diagnostic,
            fire_prevention_site_accessible,
            fire_prevention_devices,
            fire_prevention_comments,
            is_reinstallation,
            reinstallation_comments
        ) VALUES (
            'open',
            :latitude,
            :longitude,
            :address,
            :address_details,
            :fk_city,
            :built_at,
            :fk_field_type,
            :fk_owner_type,
            :population_total,
            :population_couples,
            :population_minors,
            :access_to_water,
            :trash_evacuation,
            :created_by,
            :owner,
            :declared_at,
            :census_status,
            :census_conducted_at,
            :census_conducted_by,
            :justice_rendered_by,
            :justice_rendered_at,
            :police_status,
            :police_requested_at,
            :police_granted_at,
            :bailiff,
            :justice_procedure,
            :justice_rendered,
            :justice_challenged,
            :owner_complaint,
            :fk_electricity_type,
            :water_comments,
            :electricity_comments,
            :sanitary_comments,
            :access_to_sanitary,
            :name,
            :population_minors_0_3,
            :population_minors_3_6,
            :population_minors_6_12,
            :population_minors_12_16,
            :population_minors_16_18,
            :minors_in_school,
            :water_potable,
            :water_continuous_access,
            :water_public_point,
            :water_distance,
            :water_roads_to_cross,
            :water_everyone_has_access,
            :water_stagnant_water,
            :water_hand_wash_access,
            :water_hand_wash_access_number,
            :sanitary_number,
            :sanitary_insalubrious,
            :sanitary_on_site,
            :trash_cans_on_site,
            :trash_accumulation,
            :trash_evacuation_regular,
            :vermin,
            :vermin_comments,
            :fire_prevention_measures,
            :fire_prevention_diagnostic,
            :fire_prevention_site_accessible,
            :fire_prevention_devices,
            :fire_prevention_comments,
            :is_reinstallation,
            :reinstallation_comments
        ) RETURNING shantytown_id AS id`, {
            transaction,
            replacements: {
                latitude: townData.latitude,
                longitude: townData.longitude,
                address: townData.address,
                address_details: townData.addressDetails || null,
                fk_city: townData.city,
                built_at: townData.builtAt || null,
                fk_field_type: townData.fieldType,
                fk_owner_type: townData.ownerType,
                population_total: townData.populationTotal || null,
                population_couples: townData.populationCouples || null,
                population_minors: townData.populationMinors || null,
                access_to_water: townData.accessToWater || null,
                trash_evacuation: townData.trashEvacuation || null,
                created_by: townData.createdBy,
                owner: townData.owner || null,
                declared_at: townData.declaredAt || null,
                census_status: townData.censusStatus || null,
                census_conducted_at: townData.censusConductedAt || null,
                census_conducted_by: townData.censusConductedBy || null,
                justice_rendered_by: townData.justiceRenderedBy || null,
                justice_rendered_at: townData.justiceRenderedAt || null,
                police_status: townData.policeStatus || null,
                police_requested_at: townData.policeRequestedAt || null,
                police_granted_at: townData.policeGrantedAt || null,
                bailiff: townData.bailiff || null,
                justice_procedure: townData.justiceProcedure || null,
                justice_rendered: townData.justiceRendered || null,
                justice_challenged: townData.justiceChallenged || null,
                owner_complaint: townData.ownerComplaint || null,
                fk_electricity_type: townData.electricityType || null,
                water_comments: townData.waterComments || null,
                electricity_comments: townData.electricityComments || null,
                sanitary_comments: townData.sanitaryComments || null,
                access_to_sanitary: townData.accessToSanitary || null,
                name: townData.name || null,
                population_minors_0_3: townData.populationMinors0To3 || null,
                population_minors_3_6: townData.populationMinors3To6 || null,
                population_minors_6_12: townData.populationMinors6To12 || null,
                population_minors_12_16: townData.populationMinors12To16 || null,
                population_minors_16_18: townData.populationMinors16To18 || null,
                minors_in_school: townData.minorsInSchool || null,
                water_potable: townData.waterPotable || null,
                water_continuous_access: townData.waterContinuousAccess || null,
                water_public_point: townData.waterPublicPoint || null,
                water_distance: townData.waterDistance || null,
                water_roads_to_cross: townData.waterRoadsToCross || null,
                water_everyone_has_access: townData.waterEveryoneHasAccess || null,
                water_stagnant_water: townData.waterStagnantWater || null,
                water_hand_wash_access: townData.waterHandWashAccess || null,
                water_hand_wash_access_number: townData.waterHandWashAccessNumber || null,
                sanitary_number: townData.sanitaryNumber || null,
                sanitary_insalubrious: townData.sanitaryInsalubrious || null,
                sanitary_on_site: townData.sanitaryOnSite || null,
                trash_cans_on_site: townData.trashCansOnSite || null,
                trash_accumulation: townData.trashAccumulation || null,
                trash_evacuation_regular: townData.trashEvacuationRegular || null,
                vermin: townData.vermin || null,
                vermin_comments: townData.verminComments || null,
                fire_prevention_measures: townData.firePreventionMeasures || null,
                fire_prevention_diagnostic: townData.firePreventionDiagnostic || null,
                fire_prevention_site_accessible: townData.firePreventionSiteAccessible || null,
                fire_prevention_devices: townData.firePreventionDevices || null,
                fire_prevention_comments: townData.firePreventionComments || null,
                is_reinstallation: townData.isReinstallation || null,
                reinstallation_comments: townData.reinstallationComments || null,
            },
        },
    );

    return result[0][0].id;
};
