export type ShantytownCommentRow = {
    commentId: number,
    shantytownId: number,
    commentDescription: string,
    commentCreatedAt: Date,
    commentCreatedBy: number,
    userFirstName: string,
    userLastName: string,
    userPosition: string,
    organizationId: number,
    organizationName: string,
    organizationAbbreviation: string | null,
    organization_target_name: string[],
    user_target_name: string[],
    attachments?: string[],
};
