export type ShantytownCommentRow = {
    commentId: number,
    shantytownId: number,
    commentDescription: string,
    commentCreatedAt: Date,
    commentCreatedBy: number,
    userFirstName: string,
    userLastName: string,
    userPosition: string,
    organizationId: number,
    organizationName: string,
    organizationAbbreviation: string | null,
    organization_target_name: string[],
    user_target_name: string[],
    covidCommentDate: Date,
    covidEquipeMaraude: Date,
    covidEquipeSanitaire: boolean,
    covidEquipeAccompagnement: boolean,
    covidDistributionAlimentaire: boolean,
    covidActionMediationSante: boolean,
    covidSensibilisationVaccination: boolean,
    covidEquipeMobileDepistage: boolean,
    covidEquipeMobileVaccination: boolean,
    covidPersonnesOrientees: boolean,
    covidPersonnesAvecSymptomes: boolean,
    covidBesoinAction: boolean,
};
