name: deploy-qa

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Nom de la branche Github à déployer (normalement `issue/...`)'
        required: true
        default: 'issue/'
      tag:
        description: 'Nom de l''image Docker correspondante (`qa-...`), à générer préalablement via le workflow `qa`'
        required: true
        default: 'qa-'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PREPROD_HOST }}
          username: ${{ secrets.PREPROD_USERNAME }}
          key: ${{ secrets.PREPROD_KEY }}
          port: ${{ secrets.PREPROD_PORT }}
          script: |
            cd /srv/resorption-bidonvilles
            scripts/deploy.sh ${{ github.event.inputs.branch }} ${{ github.event.inputs.tag }}