name: qa

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Nom du tag à poser sur l''image Docker. Ce tag sera par ailleurs préfixé de `qa-`'
        required: true
        default: latest

jobs:
  build-dependencies:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.dependencies
          tags: resorptionbidonvilles/dependencies:latest
          outputs: type=docker,dest=/tmp/rbdependencies.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rbdependencies
          path: /tmp/rbdependencies.tar

  build-api:
    runs-on: ubuntu-20.04
    needs: build-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load dependencies
        run: docker load --input /tmp/rbdependencies.tar
      - name: Build and push
        uses: docker/build-push-action@v2
        id: api_build
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: resorptionbidonvilles/api:qa-${{ github.event.inputs.tag }}
      - name: Image digest
        run: echo ${{ steps.api_build.outputs.digest }}

  build-www:
    runs-on: ubuntu-20.04
    needs: build-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load dependencies
        run: docker load --input /tmp/rbdependencies.tar
      - name: Build and push
        uses: docker/build-push-action@v2
        id: www_build
        with:
          context: .
          file: Dockerfile.www
          push: true
          tags: resorptionbidonvilles/www:qa-${{ github.event.inputs.tag }}
      - name: Image digest
        run: echo ${{ steps.www_build.outputs.digest }}

  build-webapp:
    runs-on: ubuntu-20.04
    needs: build-dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Load dependencies
        run: docker load --input /tmp/rbdependencies.tar
      - name: Build and push
        uses: docker/build-push-action@v2
        id: webapp_build
        with:
          context: .
          file: Dockerfile.webapp
          push: true
          tags: resorptionbidonvilles/webapp:qa-${{ github.event.inputs.tag }}
      - name: Image digest
        run: echo ${{ steps.webapp_build.outputs.digest }}
